name: CNRS-AIST JRL
# Set to true to skip CDN usage
use_local_libraries: false
plugins:
    - jekyll-octicons
    - jekyll-sitemap
    - liquefy
    - jekyll_inline_highlight
    - jekyll-toc
    - jekyll-multiple-languages-plugin
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor
    - CMakeLists.txt
    - Doxyfile.extra.in
    - setup-local-assets.sh
    - _examples
    - .gitignore
languages: ["en", "jp"]
exclude_from_localizations: ["assets", "css"]
